# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1f8c2b93387fd4b66279d6efb9ff6281985a99b1dd9e6b9046f3e32c6cba31e97e3e02d3273b539273b484e2abba005f8e0ff43f9cfa95bfc1ad4c91acafb1c

test:
  secret_key_base: f662564a0e4a1e85ff99276fbcdb6cc8a8af54236657c36397bd293aa9df29cb1436e668a2ca67227c5dceb2f6121c20e3c2a1913e829aa192a1a39b3dcd50a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
